<?php
    date_default_timezone_set('Africa/Nairobi');
    include 'blogConn.php';
    include 'cryptanalyis_Comment.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type = "text/css" href="../css/cryptanalysis.css">
    <link rel="stylesheet" type = "text/css" href="../css/index.css">
    <script type = "text/javascript" src = "../js/main.js"></script>
    <title>Cryptanalysis</title>
</head>
<body>
<div class="log-bar">
            <button onclick = "_logButton()">LOGIN</button>
            <button onclick = "_regButton()">REGISTER</button>
        </div>
        <div class = "top">
            <div  id = "p-title">Cyber<span id = "title">School</span></div>                   
            <div class="link">
                <a href="../index.php">Home</a>
                <a href="../about_us.php">About</a>
                <a href = "../login.php">Courses</a>
                <a href="../blog.php">Blog</a>
                <a href="../contact.php">Contact</a> 
            </div>
        </div>   
    <article>
        <div class="cryptanalysisContainer">
        <div>
            <h1>Cryptanalysis</h1>
            <img src="../Images/blog3.jpeg" alt="">
        </div>
        <div class="cryp_article">
            <p>
                Cryptanalysis is the study of analyzing information 
                systems in order to “discover” or “crack” the hidden 
                or secret aspects of those systems. More specifically, 
                cryptanalysis is the study of breaching cryptographic
                security systems in order to obtain access to the information
                contained within encrypted messages without necessarily knowing
                the cryptographic key used to encrypt the information. 
                The field also includes the study of targeting weaknesses 
                in the implementation of cryptographic algorithms 
                which is referred to as a side-channel attack. Throughout
                the history of the field, the methods of cryptanalysis 
                have evolved over the years to adapt to the increasing 
                complexity of algorithms in use both today and in the future.
                <h2>What Do Cryptanalysts Do?</h2>
                <div id = "p1">
                    At the fundamental level, the primary task or job of a 
                    cryptanalyst is to analyze and obtain as much information
                    about plaintext data used to generate ciphertext, or encoded text. 
                    Depending on the context of employment and goals of the organization, 
                    the work of a cryptanalyst can range from the academic to field work 
                    for various government agencies or the military.
                </div>
                <h2>How are Cryptanalysis Attacks Categorized?</h2>
                <div id="p1">
                    The primary method used to classify cryptanalysis attacks is based on 
                    the type of information available to the analyst from the cipher or crypto 
                    system under study (or attack). The basic premise of cryptanalysis is that 
                    the general algorithm is known to the person or organization undertaking the 
                    attack. This maxim is equivalent to Kerckhoff’s principle that the adversary 
                    or enemy will be able to obtain knowledge of the cipher algorithm being employed
                    through betrayal, espionage, reverse engineering, or a combination of all of 
                    these factors. At some points in the history of the cryptanalysis field of study, 
                    the cipher has been able to be fully reconstructed through pure analysis by the 
                    analysts to include the Japanese Purple code, classic encryption schemes, and 
                    the German Lorenz cipher.
                    Ciphertext Only
                    In the ciphertext only variant, the analyst is assumed to only have access to
                    a given amount of codetext or ciphertext generated by the system of interest.
                </div>
            </p>
        </div>
        </div>
    </article>
    <div class="crypta_form">
        <?php
            echo "
                <form action = '".comment($conn)."' method = 'POST'>
                    <div>
                        <input type = 'text' name = 'user_name' placeholder = 'Enter your name'>
                    </div>
                    <div>
                        <input type = 'hidden' name = 'date_time'
                        value = '".date('Y-m-d H:i:s')."'>
                    </div>
                    <div>
                        <div id = 'cry_Comment'>Comment Here</div>
                        <textarea name = 'comment'></textarea>
                    </div>
                    <div class = 'cryptanalysis_button'>
                        <button type = 'submit' name = 'cyrpComment'>Comment</button>
                    </div>
                </form>";
        ?>
    </div>
    <?php getComment($conn)?>
    <!---- Footer ---->
    <footer>
            <div class="footer_container">
                <div id="smedia">
                    <div id="subscribe">
                        <p>News Letter</p>
                        <span id = "response"></span><br>
                        <input type="text" name = "subscribe" 
                        placeholder = "Enter you email here" id = "subscriber">
                        <button type = "submit" onclick = "return false"
                        onmousedown = "subscribe();">Subscribe</button>
                    </div>
                        <br>
                        <a href="#"> <img src="../Icons/pinterest2.png" alt=""></a>
                        <a href="#"><img src="../Icons/facebook.png" alt=""></a>
                        <a href="#"><img src="../Icons/instagram.png" alt=""></a>
                        <a href="#"><img src="../Icons/youtube.png" alt=""></a>
                        <a href="#"><img src="../Icons/gmail_2.png" alt=""></a>
                        <a href="#"><img src="../Icons/linked2.png" alt=""></a> 
                        <a href="#"><img src="../Icons/twit_icon.png" alt=""></a>        
                </div>
            </div>
            <br>
            <div class="link-container">
                <div class="links">
                    <a href="../admin_login.php"> Admin</a>
                    <a href="../expert.php">Expert</a>
                    <a href="../login.php">Login</a>
                    <a href="../register.php" class = 'exclude'>Register</a>       
                </div>             
                <div id="upbtn">
                    <a href=""><img src="../Icons/upbtn.png" alt=""></a>
                </div>        
            </div>
    </footer>
</body>
</html>